config/routes.rb
ISupply::Application.routes.draw do

  resources :purchase_requests do
    member do
      get 'suggestions'
    end
  end

  resources :app_masters do
    resources :apps
    member do
      get 'distribute'
      get 'deliver'
      get 'deliver_to_offices'
    end
  end

  devise_for :users, :skip => [:registrations, :sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get '/signup' => 'registration#new', as: :new_user_registration
    post '/signup' => 'registration#create', as: :new_user_registration
    get '/users/edit' => 'devise/registrations#edit', as: :edit_user_registration
    put '/users' => 'devise/registrations#update', as: :user_registration
  end

  resources :users

  post "/users/from_profile" => "users#create_from_profile"

  post "/users/:id/roles/remove/:role" => "users#remove_role"

  post "/users/:id/roles/add/:role" => "users#add_role"

  resources :phones do
    member do
      get 'delete'
      get 'add'
    end
  end

  resources :suppliers do
    member do
      get 'add_contact'
      get 'delete_contact'
    end
  end

  resources :offices do
    resources :app_offices do
      member do
        get 'submit'
        get 'print'
      end
    end
  end
  resources :profiles

  resources :employees

  resources :colleges

  resources :items

  resources :articles

  resources :article_categories

  root :to => "site#index"

  match "/home" => "site#home"

  match 'spso_home' => 'site#spso_home'

  match "/about" => "site#about"

end

app/models/app_master.rb
class AppMaster
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes

  field :date_scheduled, :type => Date
  field :year, :type => Integer
  validates :year, numericality: {greater_than: 2000, less_than: 3000}

  accepts_nested_attributes_for :app_offices, :allow_destroy => true
  has_many :app_offices, :dependent => :destroy

  accepts_nested_attributes_for :apps, :allow_destroy => true
  has_many :apps, :dependent => :destroy

  embeds_many :app_master_lines
  accepts_nested_attributes_for :app_master_lines, :allow_destroy => true
  
  def build_app_for(offices)
    offices.each do |office|
      new_app = office.app_offices.build
      self.app_offices << new_app
      new_app.build_app_lines
      office.app_offices << new_app
      office.save!
    end
    self.save!
  end

  def apps_for_offices(office_category=nil)
    if office_category ==nil
    self.app_offices
    else
      self.app_offices.select {|app| app.office.category == office_category}
    end
  end

  def has_item?(item)
    self.app_master_lines.where(:item_id=>item.id).size!=0
  end

  def get_line(item)
    self.app_master_lines.where(:item_id=>item.id).first
  end

  def has_article_category?(article_category)
    self.app_master_lines.each do|line|
      if(line.item.article_category.eql? article_category)
      return true
      end
    end
    false
  end

  def has_article?(article)
    self.app_master_lines.each do|line|
      if(line.item.article.eql? article)
      return true
      end
    end
    false
  end
  
  def update_price_lines
    self.app_master_lines.each do|line|
      line.update_price
    end  
  end
end

class AppMasterLine
  include Mongoid::Document

  belongs_to :item

  field :price, type: BigDecimal

  embedded_in :app_master
  embedded_in :app_line
  embedded_in :pr_line
  
  def set_item(item)
    self.item = item
    update_price
  end

  def update_price
    self.price = self.item.current_price
  end
end

app/controllers/app_masters_controller.rb
class AppMastersController < ApplicationController
  # GET /app_masters
  # GET /app_masters.json
  before_filter :item_variables, :exept => [:index]
  before_filter :office_categories, :only => [:show]
  def item_variables
    @item_category = ArticleCategory.all
    @item_category.sort_by! {|c| [c.name, c.article.name,c.article.item.specification]}
    @item_hash = Item.hash_items
  end

  def office_categories
    @office_categories = Office.categories
  end

  def index
    @app_masters = AppMaster.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @app_masters }
    end
  end

  # GET /app_masters/1
  # GET /app_masters/1.json
  def show
    @app_master = AppMaster.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app_master }
    end
  end

  # GET /app_masters/new
  # GET /app_masters/new.json
  def new
    @app_master = AppMaster.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app_master }
    end
  end

  # GET /app_masters/1/edit
  def edit
    @app_master = AppMaster.find(params[:id])
  end

  # POST /app_masters
  # POST /app_masters.json
  def create
    @app_master = AppMaster.new(params[:app_master])
    update_lines_from_form

    respond_to do |format|
      if @app_master.save
        format.html { redirect_to @app_master, notice: 'App template was successfully created.' }
        format.json { render json: @app_master, status: :created, location: @app_master }
      else
        format.html { render action: "new" }
        format.json { render json: @app_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /app_masters/1
  # PUT /app_masters/1.json
  def update
    @app_master = AppMaster.find(params[:id])
    update_lines_from_form

    respond_to do |format|
      if @app_master.update_attributes(params[:app_master])
        format.html { redirect_to @app_master, notice: 'App template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_masters/1
  # DELETE /app_masters/1.json
  def destroy
    @app_master = AppMaster.find(params[:id])
    @app_master.destroy

    respond_to do |format|
      format.html { redirect_to app_masters_url }
      format.json { head :no_content }
    end
  end

  def distribute
    @app_master = AppMaster.find(params[:id])
    @offices = Office.all
  end

  def deliver
    @app_master = AppMaster.find(params[:id])
    offices = Array.new

    params[:offices].each do |office|
      offices << Office.find(:first,:conditions=>{:name=>office})
    end

    @app_master.build_app_for offices

    respond_to do |format|
      format.html { redirect_to app_master_url(@app_master) }
      format.json { head :no_content }
    end

    flash[:notice] = "Successfully delivered APP"
  end

  def deliver_to_offices
    @app_master = AppMaster.find(params[:id])
    @app_master.update_price_lines

    @app_master.build_app_for Office.all

    respond_to do |format|
      format.html { redirect_to app_master_url(@app_master) }
      format.json { head :no_content }
    end

    flash[:notice] = "Successfully delivered APP"
  end

  private

  def update_lines_from_form
    @app_master.app_master_lines.delete_all
    if(params[:selected_items])
      params[:selected_items].each do|item|
        line = @app_master.app_master_lines.build
        line.set_item Item.find(item)
      end
    end
  end

end

app/helpers/app_masters_helper.rb
module AppMastersHelper
  def sort_app_by_office(app_master)
    administrative = Array.new
    program = Array.new

    app_master.app_offices.each do|app_office|
      if(app_office.office.category==0)
      administrative << app_office
      else
      program << app_office
      end
    end

    program.each do|p|
      administrative << p
    end

    administrative
  end

  def distributed?(app_master = @app_master)
    app_master.app_offices.size != 0
  end

  def can_consolidate?(office_category)
    @app_master.app_offices.each do|app|
      if app.office.category == office_category && !app.sent
      return false
      end
    end
    true
  end

  def has_consolidated?(office_category)
    @app_master.apps.each do|app|
      if(app.office_category == office_category)
      return app
      end
    end
    nil
  end

end

app/views/app_masters/_form.html.erb
<%= form_for @app_master do |f| %>
    <% if @app_master.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@app_master.errors.count, "error") %> prohibited this app template from being saved:</h2>

          <ul>
            <% @app_master.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div>
      <label for="app_master_date_scheduled">Date Scheduled</label>
      <%= f.date_select :date_scheduled, {}, {:class => "input-small"} %>
    </div>

    <div class="field">
      <label for="app_master_year">Year</label>
      <%= select_year Date.today, {start_year: 2000, end_year: Time.now.year + 3}, {class: 'input-small', name: 'app_master[year]'}%>
    </div>
    <br/>

    <%= render "items_fields_table"%>

    <div class="form-actions">
      <input type="submit" value="<%= @app_master.new_record? ? "Create" : "Save Changes" %>" class="btn btn-primary"/>
      <%= link_to 'Back', @app_master.new_record? ? app_masters_path : app_master_path, {:class => 'btn'} %>
    </div>
<% end %>

app/views/app_masters/_item_fields.html.erb
<tr>
	<td width="1px">
	<input type = "checkbox" name = "selected_items[]" <%= "checked" if @app_master.has_item? item%> value = '<%= item.id%>'>
	</td>
	<td width="250px"> <%= item.full_name%> </td>
	<td><%= item.current_price %></td>
</tr>

app/views/app_masters/_items_fields_table.html.erb
<div class="items">
	<table class="table table-striped">
		<caption><h3>Items List</h3></caption>
		<thead>
			<tr>
				<th colspan="2">Items</th>
				<th>Price</th>
			</tr>
		</thead>
		<tbody>
			<% @item_category.each do|category| %>
			<tr >
			<td colspan="3">
				<h4> <%= category.name%>
			</td> </h4> </tr>
			<% category.articles.each do |article|%>
			<% article.items.each do |item| %>
			<%= render "item_fields", :item => item%>
			<% end %>
			<% end %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/app_masters/_items_list.html.erb
<div class="items">
	<table class="table table-striped">
		<caption>
			<h3>Items List</h3>
		</caption>
		<thead>
			<tr>
				<th width="250px">Items</th>
				<th>Price</th>
			</tr>
		</thead>
		<tbody>
			<% @item_category.each do|category| %>
			<% if @app_master.has_article_category? category %>
			<tr >
				<td colspan="2"><h4> <%= category.name%> </td> </h4>
			</tr>
			<% category.articles.each do |article|%>
			<% if @app_master.has_article? article%>
			<% article.items.each do |item| %>
			<% if @app_master.has_item? item  %>
			<tr>
				<td colspan><%= item.full_name %></td>
				<td colspan><%= @app_master.get_line(item).price %></td>
			</tr>
			<% end %>
			<% end %>
			<% end %>
			<% end %>
			<% end %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/app_masters/_office_distribution_list.html.erb
<% if distributed?  %> <h3>Office Distribution List</h3>
<div class="app_offices">
	<table class="table table-striped">
		<thead>
			<tr>
				<td width="200px">Office</td>
				<td>Remarks</td>
			</tr>
		</thead>
		<tbody>
			<% cur_cat = nil%>
			<% sort_app_by_office(@app_master).each do|app_office|%>
			<% if cur_cat != app_office.office.category %>
			<% cur_cat = app_office.office.category   %>
			<tr>
				<td colspan="2"><b><%= category_value cur_cat %></b> <% if can_consolidate? cur_cat %>
				&nbsp;
				<% app = has_consolidated? cur_cat %>
				<% if app %>
				<%= link_to 'View Consolidated APP', app_master_app_path(@app_master,app), {:class => "btn btn-success"} %>
				<% else %>
				<%= link_to 'Consolidate',new_app_master_app_path(@app_master,{:office_category=>cur_cat}), {:class=>"btn btn-primary"} %>
				<% end %>
				
				<% end %> </td>
			</tr>
			<% end %>
			<tr>
				<td><%= app_office.office.name %></td>
				<td><%= app_office.sent ? "Sumbitted at " << app_office.date_sent.to_formatted_s(:long) : "Not yet sumbitted" %></td>
			</tr>
			<% end%>
			<x/tbody>
	</table>
</div>
<% end %>

app/views/app_masters/_strip.html.erb
<div>
	<input type = "checkbox" name = "offices[]" value="<%= office.name%>">
	<%= office.name %>
</div>

app/views/app_masters/distribute.html.erb
<h1>Distribute APP no: <%= @app_master.control_number %> </span></h1>
<hr/>


<h2>Offices</h2>

<form action=<%= deliver_app_master_path(@app_master) %>>
<div>
<% @offices.each do |office|  %>
	<%= render "strip",:office=>office %>
<% end  %>
</div>
<br />

<input type="submit"  value="Send" class="btn btn-primary"/>
<%= link_to 'Back', app_master_path(@app_master), {:class=>"btn"}%>
</form>

app/views/app_masters/edit.html.erb
<h1>Edit APP Master</h1>
<hr />

<%= render 'form' %>

<%= link_to 'Show', @app_master %> |
<%= link_to 'Back', app_masters_path %>

app/views/app_masters/index.html.erb
<h1>APP Masters</h1>
<hr/>

<table class="table table-striped">
	<thead>
		<tr>
			<th width = "150px">Date scheduled</th>
			<th>Year</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @app_masters.each do |app_master| %>
		<tr>
			<td width="100px"><%= app_master.date_scheduled.to_formatted_s(:long)%></td>
			<td width="100px"><%= app_master.year %></td>
			<td><%= link_to 'Show', app_master %> |
			<% if !distributed? app_master %>
			<%= link_to 'Edit', edit_app_master_path(app_master) %> |
			<% end %>
			<%= link_to 'Destroy', app_master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<div class="form-actions">
	<%= link_to 'New App template', new_app_master_path, {:class=>"btn btn-primary"} %>
</div>

app/views/app_masters/new.html.erb
<h1>New APP Master</h1>
<hr />

<%= render 'form' %>

app/views/app_masters/show.html.erb
<h2>APP Master</h2>
<hr />

<div>
	<b>Date scheduled:&thinsp;</b>
	<%= @app_master.date_scheduled.to_formatted_s(:long) %>
</div>

<div>
	<b>Year:&thinsp;</b>
	<%= date_to_year @app_master.year%>
</div>

<%= render "items_list"%>

<%= render "office_distribution_list" %>

<div class="form-actions">
	<% if !distributed? %>
	<%= link_to 'Distribute APP', deliver_to_offices_app_master_path, {:class=>"btn btn-primary"} %>
	<%= link_to 'Edit', edit_app_master_path(@app_master), {:class => "btn"} %>
	<% end %>
	<%= link_to 'Back', app_masters_path, {:class => "btn"} %>
</div>