config/routes.rb
ISupply::Application.routes.draw do

  resources :purchase_requests do
    member do
      get 'suggestions'
    end
  end

  resources :app_masters do
    resources :apps
    member do
      get 'distribute'
      get 'deliver'
      get 'deliver_to_offices'
    end
  end

  devise_for :users, :skip => [:registrations, :sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get '/signup' => 'registration#new', as: :new_user_registration
    post '/signup' => 'registration#create', as: :new_user_registration
    get '/users/edit' => 'devise/registrations#edit', as: :edit_user_registration
    put '/users' => 'devise/registrations#update', as: :user_registration
  end

  resources :users

  post "/users/from_profile" => "users#create_from_profile"

  post "/users/:id/roles/remove/:role" => "users#remove_role"

  post "/users/:id/roles/add/:role" => "users#add_role"

  resources :phones do
    member do
      get 'delete'
      get 'add'
    end
  end

  resources :suppliers do
    member do
      get 'add_contact'
      get 'delete_contact'
    end
  end

  resources :offices do
    resources :app_offices do
      member do
        get 'submit'
        get 'print'
      end
    end
  end
  resources :profiles

  resources :employees

  resources :colleges

  resources :items

  resources :articles

  resources :article_categories

  root :to => "site#index"

  match "/home" => "site#home"

  match 'spso_home' => 'site#spso_home'

  match "/about" => "site#about"

end

app/models/office.rb
class Office
  include Mongoid::Document

  field :name, type: String
  validates :name, presence: true, length: {minimum: 2}
  
  field :category, type: Integer
  validates :category, presence: true

  accepts_nested_attributes_for :phones, allow_destroy: true
  embeds_many :phones

#  belongs_to :college
  accepts_nested_attributes_for :app_offices, allow_destroy: true
  has_many :app_offices, :dependent => :destroy
  
  has_many :purchase_requests

  def reject(attr)
  	attr[:number].blank? || attr[:type].blank?
  end
  
  def self.categories
    arr = %w{Administrative Program}
    arr.each_with_index.map {|index,value| [index,value]}
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  # GET /offices
  # GET /offices.json
  load_and_authorize_resource
  before_filter :authenticate_user!
  before_filter :phone_types, :exept => [:index, :delete_phone]
  before_filter :office_categories
  
  def phone_types
  	@phone_types = Phone.types
  end
  
  def office_categories
    @office_categories = Office.categories
  end
  
  def index
    @offices = Office.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offices }
    end
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
    @office = Office.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @office }
    end
  end

  # GET /offices/new
  # GET /offices/new.json
  def new
    @office = Office.new
	
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @office }
    end
  end

  # GET /offices/1/edit
  def edit
    @office = Office.find(params[:id])
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(params[:office])
    
  	respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Employee was successfully created.' }
        format.json { render json: @office, status: :created, location: @office }
      else
        format.html { render action: "new" }
        format.json { render json: @office.errors, status: :unprocesszable_entity }
      end
    end
  end

  # PUT /offices/1
  # PUT /offices/1.json
  def update
    @office = Office.find(params[:id])

    respond_to do |format|
      if @office.update_attributes(params[:office])
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office = Office.find(params[:id])
    @office.destroy

    respond_to do |format|
      format.html { redirect_to offices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/offices_helper.rb
module OfficesHelper
	def category_value(category)
	 @office_categories[category].first
	end
end

app/views/offices/_form.html.erb
<%= form_for(@office) do |f| %>
<% if @office.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

	<ul>
		<% @office.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<p class="name">
	<%= f.label :name %>
	<%= f.text_field :name , :placeholder => "Name"%>
</p>

<p class="category">
	<%= f.label :category %>
	<%= f.select :category, @office_categories,{}, {:class =>"input-medium"} %>
</p>

<%= render "phones/edit", :object=>@office %>
<br />

<div class="form-actions">
	<input type="submit" class="btn btn-primary" value="<%= @office.new_record? ? "Create" : "Save Changes" %>" />
	<%= link_to 'Back',  @office.new_record? ? offices_path : office_path, {:class=>:btn} %>
</div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing office</h1>
<hr />

<%= render 'form' %>

app/views/offices/index.html.erb
<h1>Offices</h1>
<hr />

<table class="table table-striped">
	<thead>
		<tr>
			<td><h3>Office name</h3></td>
		</tr>
	</thead>

	<tbody>
		<% @offices.each do |office| %>
		<tr>
			<td>
			<div>
				<%= office.name %>
				&emsp;
				<span id="line-commands"> <%= link_to 'APPs', office_app_offices_path(office) %> |
					<%= link_to 'Show', office %> |
					<%= link_to 'Edit', edit_office_path(office) %> |
					<%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %> </span>
			</div></td>
		</tr>
		<% end %>
	</tbody>
</table>

<div class="form-actions">
	<a href="<%= new_office_path%>" class="btn btn-primary">Create New Office</a>
</div>

app/views/offices/new.html.erb
<h1>New office</h1>
<hr />

<%= render 'form' %>

app/views/offices/show.html.erb
<h1>
	<%= @office.name %>
</h1>
<hr />

<div>
	<b>Category: </b>
	<%= category_value @office.category %>
</div>

<br />

<%= render "phones/show", :object => @office %>
<br />

<div class="form-actions">
<%= link_to 'View APPs', office_app_offices_path(@office), {:class=>"btn btn-primary"} %>
<%= link_to 'Edit', edit_office_path(@office), {:class=>"btn"} %>
<%= link_to 'Back', offices_path, {:class=>"btn"} %>
</div>