config/routes.rb
ISupply::Application.routes.draw do

  resources :purchase_requests do
    member do
      get 'suggestions'
    end
  end

  resources :app_masters do
    resources :apps
    member do
      get 'distribute'
      get 'deliver'
      get 'deliver_to_offices'
    end
  end

  devise_for :users, :skip => [:registrations, :sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get '/signup' => 'registration#new', as: :new_user_registration
    post '/signup' => 'registration#create', as: :new_user_registration
    get '/users/edit' => 'devise/registrations#edit', as: :edit_user_registration
    put '/users' => 'devise/registrations#update', as: :user_registration
  end

  resources :users

  post "/users/from_profile" => "users#create_from_profile"

  post "/users/:id/roles/remove/:role" => "users#remove_role"

  post "/users/:id/roles/add/:role" => "users#add_role"

  resources :phones do
    member do
      get 'delete'
      get 'add'
    end
  end

  resources :suppliers do
    member do
      get 'add_contact'
      get 'delete_contact'
    end
  end

  resources :offices do
    resources :app_offices do
      member do
        get 'submit'
        get 'print'
      end
    end
  end
  resources :profiles

  resources :employees

  resources :colleges

  resources :items

  resources :articles

  resources :article_categories

  root :to => "site#index"

  match "/home" => "site#home"

  match 'spso_home' => 'site#spso_home'

  match "/about" => "site#about"

end

app/models/item.rb
class Item
  include Mongoid::Document

  resourcify

  attr_accessor :current_code

  field :code, type: String
  validates :code, presence: true

  field :stock_number, type: String
  validates :stock_number, presence: true

  field :specification, type: String, default: ''
  validates :specification, presence: true

  field :price, type: BigDecimal
  validates :price, presence: true

  field :unit, type: String
  validates :unit, presence: true

  belongs_to :article, autosave: true

  accepts_nested_attributes_for :article
  validates :article, presence: true

  delegate :article_category, to: :article

  validate :unique_item, on: :create
  validate :unique_item_code

  before_create :save_association, :tire_index

  has_and_belongs_to_many :suppliers, :dependent => :destroy

  embeds_many :item_prices

  def code=(c)
    write_attribute(:code, c.capitalize)
  end

  # Tire related
  #include Tire::Model::Search
  #include Tire::Model::Callbacks
  def tire_index

    #items = [self]
    #
    #Tire.index 'items' do
    #  import items
    #
    #  create
    #  items.each do |item|
    #    store id: item.id, specification: item.specification, article: item.article.name
    #  end
    #end
  end

  def update_price(price)
    self.item_prices.find_or_create_by_value(price)
  end

  def current_price
    if(self.item_prices.size==0)
      return price
    end
    self.item_prices.last
  end

  def to_indexed_json
    self.as_json
  end

  def increment_code

    article.incr_code

    if (article.code > article_category.last_code)
      article_category.last_code = article.code
    end
  end

  def self.hash_items
    items = all
    temp = items.map { |item| [item.id, "#{item.full_name}"] }
    Hash[*temp.flatten]
  end

  def self.hash_full_name
    items = all
    temp = items.map { |item| ["#{item.full_name}", item.id] }
    Hash[*temp.flatten]
  end

  def self.array_typeahead
    all.map { |item| item.full_name }
  end

  def full_name
    "#{self.article.name.upcase} #{self.specification}"
  end

  def stock_number
    if !article.nil?
      "#{article_category.code}-#{"%03d" % article.code}-#{code}"
    else
      ''
    end
  end

  private

  def save_association
    article_category.save
    article.save
  end

  def unique_item
    if Item.exists?(conditions: {specification: specification, unit: unit, article_id: article.id})
      errors.add(:id, "Item already exists.")
    end
  end

  def unique_item_code
    if Item.where(:_id.ne => id, article_id: article.id, code: code).exists?
      errors.add(:code, "exists on the same article")
    end
  end

  before_save :increment_code

end

class ItemPrice
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  field :value, type: BigDecimal
  validates :value, presence: true, uniqueness: true

  embedded_in :item
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

#  load_and_authorize_resource
  before_filter :authenticate_user!

  # GET /items
  # GET /items.json
  def index

    #q = params[:q]
    #if !q.nil? and !q.empty?
    #  query = q + "*"
    #
    #  s = Tire.search 'items' do
    #    query do
    #      string "specification:#{query} OR article:#{query}"
    #    end
    #  end
    #
    #  @items = s.results.map do |doc|
    #    Item.find(doc.id)
    #  end
    #
    #  #
    #  #@items = Item.tire.search load: true do
    #  #  query do
    #  #    string "specification:#{query} OR article:#{query}"
    #  #  end
    #  #end
    #else
    @items = Item.all
    #end

    @categories = ArticleCategory.all

    @article_category = ArticleCategory.new

    @result = @items.group_by do |item|
      item.article
    end.group_by do |article, items|
      article.article_category
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @result }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show

    if can? :edit, Item
      redirect_to action: :edit
    else
      @item = Item.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @item }
      end
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    if !params[:aid].nil?
      @article = Article.find(params[:aid])

      if !@article.nil?
        @category = @article.article_category
        @item.article = @article
        @item.code = @article.next_item_code
      else
        @article = Article.new
        @category = ArticleCategory.new
      end
    elsif  !params[:cid].nil?
      @category = ArticleCategory.find(params[:cid])
      @category = ArticleCategory.new if @category.nil?
      @article = Article.new
    else
      @category = ArticleCategory.new
      @article = Article.new
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end


  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
    @article = @item.article
    @category = @article.article_category

    if @item.code.nil?
       @item.code = @article.next_item_code
    end
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    @article = Article.find_or_initialize_by(name: params[:article][:name])
    @article.assign_attributes(params[:article])

    @category = ArticleCategory.find_or_initialize_by(name: params[:category][:name])
    @category.assign_attributes(params[:category])

    @article.article_category = @category
    @item.article = @article

    respond_to do |format|
      if @item.valid? & @article.valid? & @category.valid?

        @item.save

        format.html { redirect_to items_path }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])
    @item.assign_attributes(params[:item])

    @article = @item.article
    @article.assign_attributes(params[:article])

    @category = @article.article_category
    @category.assign_attributes(params[:category])

    respond_to do |format|
      if @item.valid? & @article.valid? & @category.valid?

        @item.save # Autosave is enable

        format.html { redirect_to items_path }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :ok }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def item_value(id)
    @item_hash[id]
  end

  def has_article(object, article)
    object.items.each do|item|
      if(item.article.name.eql? article.name)
      return true
      end
    end
    false
  end

  def has_category(object, category)
    object.items.each do|item|
      if(item.article.article_category.name.eql? category.name)
      return true
      end
    end
    false
  end

end

app/views/items/_form.html.erb
<%= javascript_include_tag "jquery-ui.autocomplete" -%>
<%= javascript_include_tag "items-form" -%>
<%= javascript_include_tag 'article-category' %>
<%= stylesheet_link_tag "jquery.ui.autocomplete-bootstrap" -%>

<%= form_for @item, html: {class: "form-item form-horizontal span6 offset3"} do |f| %>

    <% if @item.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @item.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% if @category.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <!------------------------ Article Category ------------------------>

    <div class="control-group">
      <div class="control-label">Category Name</div>
      <div class="controls">
        <input id="category-name" name="category[name]" size="30" type="text" value="<%= @category.name -%>"/>
      </div>
    </div>

    <div class="control-group">
      <div class="control-label"> Code</div>
      <div class="controls">
        <input id="category-code" name="category[code]" size="30" type="text" value="<%= @category.code -%>"/>
      </div>
    </div>

    <!------------------------ Article ------------------------>

    <div class="control-group">
      <div class="control-label">Article Name</div>
      <div class="controls">
        <input name="article[name]" size="30" type="text" value="<%= @article.name -%>"/>
      </div>
    </div>

    <div class="control-group">
      <div class="control-label">Code</div>
      <div class="controls">
        <% if current_page? new_item_path %>
            <input name="article[code]" size="30" type="text" value="<%= @category.last_code + 1-%>"/>
        <% else %>
            <input name="article[code]" size="30" type="text" value="<%= @article.code -%>"/>
        <% end %>
      </div>
    </div>

    <!------------------------ Item ------------------------>
    <div class="control-group">
      <div class="control-label">Item Code</div>
      <div class="controls">
        <input id="item_code" name="item[code]" size="30" type="text" value="<%= @item.code-%>"/>
      </div>
    </div>

    <div class="control-group">
      <div class="control-label">Stock #</div>
      <div class="controls">
        <input id="item_stock_number" type="text" value="<%= @item.stock_number %>" readonly=""/>
      </div>
    </div>

    <div class="control-group">
      <div class="control-label">Specification</div>
      <div class="controls">
        <input id="item_specification" name="item[specification]" size="30" type="text" value="<%= @item.specification -%>"/>
      </div>
    </div>

    <div class="control-group">
      <div class="control-label"> Unit</div>
      <div class="controls">
        <input name="item[unit]" size="30" type="text" value="<%= @item.unit -%>"/>
      </div>
    </div>

    <div class="control-group">
      <div class="control-label">Price</div>
      <div class="controls">
        <input id="item_price" name="item[price]" size="30" type="text" value="<%= @item.price -%>"/>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
<% end %>

app/views/items/_item_fields.html.erb
<tr>
	<td width="1px">
	<input type = "checkbox" name = "selected_items[]" <%= "checked" if object.items.include? item%> value = '<%= item.id%>'>
	</td>
	<td width="250px"> <%= item.full_name%> </td>
	<td><%= item.price %></td>
</tr>

app/views/items/_items_fields_table.html.erb
<div class="items">
	<table class="table table-striped">
		<caption><h3>Items List</h3></caption>
		<thead>
			<tr>
				<th colspan="2">Items</th>
				<th>Price</th>
			</tr>
		</thead>
		<tbody>
			<% @item_category.each do|category| %>
			<tr >
			<td colspan="3">
				<h4> <%= category.name%>
			</td> </h4> </tr>
			<% category.articles.each do |article|%>
			<% article.items.each do |item| %>
			<%= render "items/item_fields", :item => item, :object => object%>
			<% end %>
			<% end %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/items/_items_list.html.erb
<div class="items">
	<table class="table table-striped">
		<thead>
			<tr>
				<td colspan="3"><h3>Items List</h3></td>
			</tr>
		</thead>
		<tbody>
			<% @item_category.each do|category| %>
			<% if has_category object, category %>
			<tr >
				<td colspan="3" style="text-align:center; vertical-align:middle"><h4> <%= category.name%> </td> </h4>
			</tr>
			<% category.articles.each do |article|%>
			<% if(has_article object, article) %>
			<tr>
				<td colspan="3"> <%= article.name%> </td>
			</tr>
			<% article.items.each do |item| %>
			<% if object.items.include? item  %>
			<tr>
				<td width="20px"></td>
				<td colspan="2"><%= item.specification %></td>
			</tr>
			<% end %>
			<% end %>
			<% end %>
			<% end %>
			<% end %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<%= javascript_include_tag "items" %>
<%= javascript_include_tag "jquery.contextMenu" %>
<%= stylesheet_link_tag "jquery.contextMenu" -%>
<%= stylesheet_link_tag "items" -%>

<div class="span12 pull-left">
  <h2 class="pull-left">Items</h2>

  <div class="add-item">
    <a href="<%= new_item_url %>" class="btn"><i class="icon-plus"></i> Item</a>
  </div>
</div>

<nav class="category pull-left">
  <h3>Categories</h3>
  <ul class="">
    <% @categories.each do |cat| %>
        <li class="cat">
          <a href="<%= edit_article_category_path(cat) %>"><%= cat.name %></a>
        </li>
        <li class="add-item">
          <a class="add-item-cat" href="<%= new_item_url %>?cid=<%= cat.id %>"><i class="icon-plus"></i> Item</a>
        </li>
    <% end %>
  </ul>
  <div class="new-category">
      <a href="#new-category-modal" data-toggle="modal"><i class="icon-plus"></i> Category</a>

    <div id="new-category-modal" class="modal fade hide">
      <div class="modal-header"><h3>New Article Category</h3></div>
      <div class="modal-body"><%= render 'article_categories/form' %></div>
    </div>
  </div>
</nav>

<div class="items">
  <header>
    <h3 class="pull-left">Articles and Specifications</h3>
    <!--<form class="form form-search pull-right">-->
    <!--<input type="text" placeholder="Search Articles">-->
    <!--</form>-->
  </header>

  <%- @result.each do |cat, articles| -%>
      <div class="category-items">
        <header>
          <div class="category">
            <%= cat.name %>
            <a class="add-item-cat" href="<%= new_item_url %>?cid=<%= cat.id %>"><i class="icon-plus"></i> Item</a>
          </div>
          <div class="stock-number">Stock #</div>
          <div class="unit-price">Unit Price</div>
        </header>
        <ul class="items">
          <% articles.each do |article, items| %>
              <% items.each do |item| %>
                  <li class="item">
                    <a href=<%= item_path(item) %>>
                      <div class="item">
                        <span class="article"><%= article.name %></span>,
                        <span class="specification"><%= item.specification %></span>
                      </div>
                      <div class="stock-number"><%= item.stock_number %></div>
                      <div class="unit-price">P <%= item.price %>/ <%= item.unit %></div>
                    </a>
                  </li>
                  <li class="add-item">
                    <a  href="<%= new_item_url %>?aid=<%= article.id %>"><i class="icon-plus"></i> Item</a>
                  </li>
              <% end %>
          <% end %>
        </ul>
      </div>
  <% end %>
</div>

app/views/items/new.html.erb
<h2>New Item</h2>

<%= render 'form' %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stock number:</b>
  <%= @item.stock_number %>
</p>

<p>
  <b>Specification:</b>
  <%= @item.specification %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>