config/routes.rb
ISupply::Application.routes.draw do

  resources :purchase_requests do
    member do
      get 'suggestions'
    end
  end

  resources :app_masters do
    resources :apps
    member do
      get 'distribute'
      get 'deliver'
      get 'deliver_to_offices'
    end
  end

  devise_for :users, :skip => [:registrations, :sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get '/signup' => 'registration#new', as: :new_user_registration
    post '/signup' => 'registration#create', as: :new_user_registration
    get '/users/edit' => 'devise/registrations#edit', as: :edit_user_registration
    put '/users' => 'devise/registrations#update', as: :user_registration
  end

  resources :users

  post "/users/from_profile" => "users#create_from_profile"

  post "/users/:id/roles/remove/:role" => "users#remove_role"

  post "/users/:id/roles/add/:role" => "users#add_role"

  resources :phones do
    member do
      get 'delete'
      get 'add'
    end
  end

  resources :suppliers do
    member do
      get 'add_contact'
      get 'delete_contact'
    end
  end

  resources :offices do
    resources :app_offices do
      member do
        get 'submit'
        get 'print'
      end
    end
  end
  resources :profiles

  resources :employees

  resources :colleges

  resources :items

  resources :articles

  resources :article_categories

  root :to => "site#index"

  match "/home" => "site#home"

  match 'spso_home' => 'site#spso_home'

  match "/about" => "site#about"

end

app/views/apps/_annual_table_listing.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th width="200px">Items</th>
			<th width="50px">Price</th>
			<% @app.app_offices.each do|app| %>
			<th><%= app.office.name %></th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% ctr = 0 %>
		<% @item_category.each do|category| %>
		<% if @app_master.has_article_category? category %>
		<tr>
			<td colspan="<%= @app.app_offices.size+2 %>"><h5><%= category.name %></h5></td>
		</tr>
		<% category.articles.each do|article| %>
		<% if @app_master.has_article? article %>
		<% article.items.each do|item| %>
		<% if @app_master.has_item? item  %>
		<%= render "table_line", :line => @app_master.get_line(item), :ctr => ctr%>
		<% ctr+=1 %>
		<% end %>
		<% end %>
		<% end %>
		<% end %>
		<% end %>
		<% end %>
	</tbody>
</table>

app/views/apps/_form.html.erb
<%= form_for [@app_master,@app] do |f| %>
<% if @app.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

	<ul>
		<% @app.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div>
	<b>Type:</b> <%= category_value @app.office_category %>
	<%= f.text_field :office_category, {:type=>"hidden"} %>
</div>
<br />

<div class="field">
	<b>Control number:</b> &nbsp;
	<%= f.text_field :control_number, {:class => "input-small"} %>
</div>

<br />

<%= render "annual_table_listing"%>

<div class="form-actions">
	<input type="submit" value="<%= @app.new_record? ? "Create" : "Save Changes" %>" class="btn btn-primary"/>
	<%= link_to 'Back', app_master_apps_path , {:class=>"btn"}%>
</div>
<% end %>

app/views/apps/_table_line.html.erb
<tr>
	<td><%= line.item.full_name %></td>
	<td><%= line.price %></td>
	<% @app.app_offices.each_with_index do|office,index|  %>
		<td><%= @annual_listing[index][ctr] %></td>
	<% end %>
</tr>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th>Control number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= app.control_number %></td>
    <td><%= link_to 'Show', app %></td>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New Consolidated APP</h1>
<hr />

<%= render 'form' %>

app/views/apps/show.html.erb
<h1>Consolidated APP</h1>
<hr/>

<div>
	<b>Control number:</b>
	<%= @app.control_number %>
</div>
<br />

<%= render "annual_table_listing"%>

<div class="form-actions">
	<%= link_to 'Make PR', new_purchase_request_path({:class=>App,:object_id=>@app}), {:class=>"btn btn-primary"} %>
	<%= link_to 'Back', app_master_path(@app_master), {:class => "btn"} %>
</div>